from setuptools import setup

setup(
    name = "metrix_ml",
    version = "0.0.1",
    author = "Melanie Vollmar",
    author_email = "melanie.vollmar@diamond.ac.uk",
    description = "A package which uses crystallographic statistics and metrics \n"
    							"to make predictions about the likelihood of solving a structure",
    license = "BSD",
    keywords = "awesome python package",
    packages=[
      'metrix_ml'
    ],
    scripts=[
      'bin/decisiontree/decisiontree_bag_randomsearch_newdata_minusEP',
      'bin/decisiontree/decisiontree_bag_randomsearch_topFeatures',
      'bin/decisiontree/decisiontree_bag_randomsearch_best_threshold',
      'bin/decisiontree/decisiontree_bag_randomsearch_best_retrain',
      'bin/decisiontree/decisiontree_bag_randomsearch_MR',
      'bin/decisiontree/decisiontree_bag_randomsearch_topfeatures_MR',
      'bin/randomforest/extreme_randomforest_randomsearch_newdata_minusEP',
      'bin/randomforest/extreme_randomforest_randomsearch_topFeatures',
      'bin/randomforest/extreme_randomforest_randomsearch_best_threshold',
      'bin/randomforest/extreme_randomforest_randomsearch_MR',
      'bin/randomforest/extreme_randomforest_randomsearch_topfeatures_MR',
      'bin/randomforest/randomforest_randomsearch_newdata_minusEP',
      'bin/randomforest/randomforest_randomsearch_topFeatures',
      'bin/randomforest/randomforest_randomsearch_best_threshold',
      'bin/randomforest/randomforest_randomsearch_best_retrain',
      'bin/randomforest/randomforest_randomsearch_MR',
      'bin/randomforest/randomforest_randomsearch_topfeatures_MR',
      'bin/decisiontree/decisiontree_ada_randomsearch_newdata_minusEP',
      'bin/decisiontree/decisiontree_ada_randomsearch_topFeatures',
      'bin/decisiontree/decisiontree_ada_randomsearch_best_threshold',
      'bin/decisiontree/decisiontree_ada_randomsearch_best_retrain',
      'bin/decisiontree/decisiontree_ada_randomsearch_MR',
      'bin/decisiontree/decisiontree_ada_randomsearch_topfeatures_MR',
      'bin/pre_processing/feature_correlations_newdata_minusEP',
      'bin/pre_processing/pca_newdata_minusEP',
      'bin/pre_processing/recursive_feature_elimination_SVM_newdata_minusEP',
      'bin/pre_processing/polynomial_features_newdata_minusEP',
      'bin/pre_processing/feature_analysis_plotting',
      'bin/pre_processing/feature_pairplot_plotting',
      'bin/pre_processing/feature_correlations_MR',
      'bin/pre_processing/pca_MR',
      'bin/pre_processing/recursive_feature_elimination_SVM_MR',
      'bin/pre_processing/polynomial_features_MR',
      'bin/pre_processing/feature_analysis_plotting_MR',
      'bin/pre_processing/feature_pairplot_plotting_MR',
      'bin/svm/svm_linear_randomsearch_newdata_minusEP',
      'bin/svm/svm_linear_randomsearch_topFeatures',
      'bin/svm/svm_linear_randomsearch_best_threshold',
      'bin/svm/svm_linear_randomsearch_MR',
      'bin/svm/svm_linear_randomsearch_topfeatures_MR',
      'bin/svm/svm_rbf_randomsearch_newdata_minusEP',
      'bin/svm/svm_rbf_randomsearch_topFeatures',
      'bin/svm/svm_rbf_randomsearch_best_threshold',
      'bin/svm/svm_rbf_randomsearch_MR',
      'bin/svm/svm_rbf_randomsearch_topfeatures_MR',
      'bin/decisiontree/decisiontree_randomsearch_newdata_minusEP',
      'bin/decisiontree/decisiontree_randomsearch_best_threshold',
      'bin/decisiontree/decisiontree_randomsearch_topFeatures',
      'bin/decisiontree/decisiontree_randomsearch_holdout35',
      'bin/decisiontree/decisiontree_randomsearch_MR',
      'bin/decisiontree/decisiontree_randomsearch_topfeatures_MR',
      'bin/predict/predict_with_standardisation',
      'bin/predict/predict_without_standardisation',
      'bin/predict/predict_without_standardisation_MR',
      'bin/calibrate/calibrate',
      'bin/calibrate/calibrate_MR',
      'bin/calibrate/calibrate_scaled',
      'bin/voting/voting',
      'bin/voting/voting_retrain',
      'bin/k_means_clustering/k_means_clustering',
      'bin/dbscan_clustering/dbscan_clustering'
    ],
    install_requires=[
      'matplotlib==3.1.0',
      'pandas',
      'pytest',
      'sklearn',
      'scikit-plot',
      'scipy',
      'mlxtend',
      'joblib'
     ],
    classifiers=[
        "Development Status :: 3 - Alpha",
        "License :: OSI Approved :: BSD License",
    ],
)
