from setuptools import setup

setup(
    name = "metrix_ml",
    version = "0.0.1",
    author = "Melanie Vollmar",
    author_email = "melanie.vollmar@diamond.ac.uk",
    description = "A package which uses crystallographic statistics and metrics \n"
    							"to make predictions about the likelihood of solving a structure",
    license = "BSD",
    keywords = "awesome python package",
    packages=[
      'metrix_ml'
    ],
    scripts=[
      'bin/decisiontree/decisiontree_bag_randomsearch_newdata_minusEP',
      'bin/decisiontree/decisiontree_bag_randomsearch_newdata_minusEP_proc',
      'bin/decisiontree/decisiontree_bag_randomsearch_newdata_minusEP_screen',
      'bin/decisiontree/decisiontree_bag_randomsearch_newdata_minusEP_tummyfeatures',
      'bin/decisiontree/decisiontree_bag_randomsearch_newdata_minusEP_top_Feature1_3_5_Data2',
      'bin/decisiontree/decisiontree_bag_randomsearch_newdata_minusEP_top_Feature1_3_5_Data2_threshold',
      'bin/decisiontree/decisiontree_bag_randomsearch_best_threshold',
      'bin/decisiontree/decisiontree_bag_randomsearch_best_retrain',
      'bin/randomforest/extreme_randomforest_randomsearch_newdata_minusEP',
      'bin/randomforest/extreme_randomforest_randomsearch_newdata_minusEP_proc',
      'bin/randomforest/extreme_randomforest_randomsearch_newdata_minusEP_screen',
      'bin/randomforest/extreme_randomforest_randomsearch_newdata_minusEP_tummyfeatures',
      'bin/randomforest/extreme_randomforest_randomsearch_newdata_minusEP_top_Feature1_3_5_Data2',
      'bin/randomforest/extreme_randomforest_randomsearch_newdata_minusEP_top_Feature1_3_5_Data2_threshold',
      'bin/randomforest/extreme_randomforest_randomsearch_best_threshold',
      'bin/randomforest/randomforest_randomsearch_newdata_minusEP',
      'bin/randomforest/randomforest_randomsearch_newdata_minusEP_proc',
      'bin/randomforest/randomforest_randomsearch_newdata_minusEP_screen',
      'bin/randomforest/randomforest_randomsearch_newdata_minusEP_tummyfeatures',
      'bin/randomforest/randomforest_randomsearch_newdata_minusEP_top_Feature1_3_5_Data2',
      'bin/randomforest/randomforest_randomsearch_newdata_minusEP_top_Feature1_3_5_Data2_threshold',
      'bin/randomforest/randomforest_randomsearch_best_threshold',
      'bin/randomforest/randomforest_randomsearch_best_retrain',
      'bin/decisiontree/decisiontree_ada_randomsearch_newdata_minusEP',
      'bin/decisiontree/decisiontree_ada_randomsearch_newdata_minusEP_proc',
      'bin/decisiontree/decisiontree_ada_randomsearch_newdata_minusEP_screen',
      'bin/decisiontree/decisiontree_ada_randomsearch_newdata_minusEP_tummyfeatures',
      'bin/decisiontree/decisiontree_ada_randomsearch_newdata_minusEP_top_Feature1_3_5_Data2',
      'bin/decisiontree/decisiontree_ada_randomsearch_newdata_minusEP_top_Feature1_3_5_Data2_threshold',
      'bin/decisiontree/decisiontree_ada_randomsearch_best_threshold',
      'bin/decisiontree/decisiontree_ada_randomsearch_best_retrain',
      'bin/pre_processing/feature_correlations_newdata',  
      'bin/pre_processing/feature_correlations_newdata_minusEP',
      'bin/pre_processing/feature_correlations_newdata_minusEP_proc',
      'bin/pre_processing/feature_correlations_newdata_minusEP_screen',
      'bin/pre_processing/feature_correlations_newdata_minusEP_tummyfeatures',
      'bin/pre_processing/feature_correlations_newdata_minusEP_top_Feature1_3_5_Data2',
      'bin/pre_processing/pca_newdata',
      'bin/pre_processing/pca_newdata_minusEP',
      'bin/pre_processing/pca_newdata_minusEP_proc',
      'bin/pre_processing/pca_newdata_minusEP_screen',
      'bin/pre_processing/pca_newdata_minusEP_tummyfeatures',
      'bin/pre_processing/recursive_feature_elimination_SVM_newdata',
      'bin/pre_processing/recursive_feature_elimination_SVM_newdata_minusEP',
      'bin/pre_processing/recursive_feature_elimination_SVM_newdata_minusEP_screen',
      'bin/pre_processing/recursive_feature_elimination_SVM_newdata_minusEP_proc',
      'bin/pre_processing/recursive_feature_elimination_SVM_newdata_minusEP_tummyfeatures',
      'bin/pre_processing/polynomial_features_newdata',
      'bin/pre_processing/polynomial_features_newdata_minusEP',
      'bin/pre_processing/polynomial_features_newdata_minusEP_proc',
      'bin/pre_processing/polynomial_features_newdata_minusEP_screen',
      'bin/pre_processing/polynomial_features_newdata_minusEP_tummyfeatures',
      'bin/svm/svm_linear_randomsearch_newdata_minusEP',
      'bin/svm/svm_linear_randomsearch_newdata_minusEP_proc',
      'bin/svm/svm_linear_randomsearch_newdata_minusEP_screen',
      'bin/svm/svm_linear_randomsearch_newdata_minusEP_tummyfeatures',
      'bin/svm/svm_linear_randomsearch_newdata_minusEP_top_Feature1_3_5_Data2',
      'bin/svm/svm_linear_randomsearch_newdata_minusEP_top_Feature1_3_5_Data2_threshold',
      'bin/svm/svm_linear_randomsearch_best_threshold',
      'bin/svm/svm_rbf_randomsearch_newdata_minusEP_proc',
      'bin/svm/svm_rbf_randomsearch_newdata_minusEP_screen',
      'bin/svm/svm_rbf_randomsearch_newdata_minusEP_tummyfeatures',
      'bin/svm/svm_rbf_randomsearch_newdata_minusEP_top_Feature1_3_5_Data2',
      'bin/svm/svm_rbf_randomsearch_newdata_minusEP_top_Feature1_3_5_Data2_threshold',
      'bin/svm/svm_rbf_randomsearch_best_threshold',
      'bin/decisiontree/decisiontree_randomsearch_newdata',
      'bin/decisiontree/decisiontree_randomsearch_newdata_minusEP',
      'bin/decisiontree/decisiontree_randomsearch_newdata_minusEP_proc',
      'bin/decisiontree/decisiontree_randomsearch_newdata_minusEP_screen',
      'bin/decisiontree/decisiontree_randomsearch_newdata_minusEP_tummyfeatures',
      'bin/decisiontree/decisiontree_randomsearch_newdata_minusEP_top_Feature1_3_5_Data2',
      'bin/decisiontree/decisiontree_randomsearch_newdata_minusEP_top_Feature1_3_5_Data2_threshold',
      'bin/decisiontree/decisiontree_randomsearch_best_threshold',
      'bin/naive_bayes/naive_bayes_randomsearch_newdata_minusEP',
      'bin/kneighbors/kneighbors_randomsearch_newdata_minusEP',
      'bin/kneighbors/kneighbors_randomsearch_newdata_minusEP_proc',
      'bin/kneighbors/kneighbors_randomsearch_newdata_minusEP_screen',
      'bin/kneighbors/kneighbors_randomsearch_newdata_minusEP_tummyfeatures',
      'bin/predict/predict_with_standardisation',
      'bin/predict/predict_without_standardisation',
      'bin/calibrate/calibrate',
      'bin/voting/voting',
      'bin/voting/voting_retrain'
    ],
    install_requires=[
      'matplotlib',
      'pandas',
      'pytest',
      'sklearn',
      'scikit-plot',
      'scipy',
      'mlxtend'
     ],
    classifiers=[
        "Development Status :: 3 - Alpha",
        "License :: OSI Approved :: BSD License",
    ],
)
